import Head from "next/head"

export default function Meta({title}) {
  return (
    <>
      <Head>
        <title>{title} - Tech24</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}